const guias= [
    {
        foto: "imgGuias/danielita.jpg",
        id: "G56451" ,
        Nombre: "Daniela",
        Edad: 26,
        genero: "femenino",
        procedencia: "colombian",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:3,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/andres.jpg",
        id: "G23893" ,
        Nombre: "Andres",
        Edad: 30,
        genero: "masculino",
        procedencia: "colombian",
        idioma:["español","ingles"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/luisa.jpg",
        id: "G63489" ,
        Nombre: "Luisa",
        Edad: 20,
        genero: "femenino",
        procedencia: "colombian",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:1,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/angel.jpg",
        id: "G19841981" ,
        Nombre: "Angel",
        Edad: 28,
        genero: "masculino",
        procedencia: "argentino",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:4,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/victor.jpg",
        id: "G48151" ,
        Nombre: "Victor",
        Edad: 35,
        genero: "masculino",
        procedencia: "colombiano",
        idioma:["ingles"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:3,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/julian.jpg",
        id: "G28465" ,
        Nombre: "Julian",
        Edad: 18,
        genero: "masculino",
        procedencia: "colombiano",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:4,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/tomas.jpg",
        id: "G1841656" ,
        Nombre: "tomas",
        Edad: 18,
        genero: "masculino",
        procedencia: "americano",
        idioma:["español","ingles"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:3,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/cristian.jpg",
        id: "G28465" ,
        Nombre: "Cristian",
        Edad: 32,
        genero: "masculino",
        procedencia: "colombiano",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:3,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/felipe.jpg",
        id: "G198465" ,
        Nombre: "Felipe",
        Edad: 22,
        genero: "masculino",
        procedencia: "colombiano",
        idioma:["español"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:13,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        foto: "imgGuias/manu.jpg",
        id: "G1165165" ,
        Nombre: "Manuela",
        Edad: 22,
        genero: "femenino",
        procedencia: "americano",
        idioma:["ingles"],
        telefono: 64812,
        correo: "debfew@uwehcuweche.com",
        anosExperiencia:3,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },

];

const tours= [
    {
        foto: "/imagenes/TOURS/arquitectura-unica.jpg",
        idTour: "tu1" ,
        nombre: "Arquitectura en Medellin",
        idioma:["español"],
        idGuia:"G56451",
        correo: "debfew@uwehcuweche.com",
        categorias:["Gastronomia","cultura"],
        duracion: 5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
        descripcionMin: " ",
    },
    {
        foto: "/imagenes/TOURS/el-camino-de-los-abuelos.jpg",
        idTour: "tu1" ,
        nombre: "Camino de los abuelos",
        idioma:["español", "Ingles"],
        idGuia:"G56451",
        correo: "debfew@uwehcuweche.com",
        categorias:["Gastronomia","cultura"],
        duracion: 5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
        descripcionMin: "Del pueblo a la ciudad",
    },
    {
        foto: "./imagenes/TOURS/tour-innovacion-social.jpg",
        idTour: "tu1" ,
        nombre: "Tour innovación social",
        idioma:["español", "Ingles"],
        idGuia:"G56451",
        correo: "debfew@uwehcuweche.com",
        categorias:["Gastronomia","cultura"],
        duracion: 5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
        descripcionMin: " ",
    },
    {
        foto: "/imagenes/TOURS/arquitectura-unica.jpg",
        idTour: "tu1" ,
        nombre: "Arquitectura en Medellin",
        idioma:["español"],
        idGuia:"G56451",
        correo: "debfew@uwehcuweche.com",
        categorias:["Gastronomia","cultura"],
        duracion: 5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
        descripcionMin: " ",
    },
    {
        foto: "/imagenes/TOURS/arquitectura-unica.jpg",
        idTour: "tu1" ,
        nombre: "Arquitectura en Medellin",
        idioma:["español"],
        idGuia:"G56451",
        correo: "debfew@uwehcuweche.com",
        categorias:["Gastronomia","cultura"],
        duracion: 5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
        descripcionMin: " ",
    },
    {
        foto: "img/caminoDeLosAbuelos.png",
        idTour: "tu1" ,
        nombre: "Camino de los abuelos",
        idioma:["español", "Ingles"],
        idGuia:"G56451",
        correo: "debfew@uwehcuweche.com",
        categorias:["Gastronomia","cultura"],
        duracion: 5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
        descripcionMin: "Del pueblo a la ciudad",
    },
    {
        foto: "./imagenes/TOURS/comuna-13-operacion-orion.jpg",
        idTour: "tu1" ,
        nombre: "Tour innovación social",
        idioma:["español", "Ingles"],
        idGuia:"G56451",
        correo: "debfew@uwehcuweche.com",
        categorias:["Gastronomia","cultura"],
        duracion: 5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
        descripcionMin: " ",
    },
    {
        foto: "./imagenes/TOURS/arquitectura-unica.jpg",
        idTour: "tu1" ,
        nombre: "Arquitectura en Medellin",
        idioma:["español"],
        idGuia:"G56451",
        correo: "debfew@uwehcuweche.com",
        categorias:["Gastronomia","cultura"],
        duracion: 5,
        descripcion:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
        descripcionMin: " ",
    },
];

const reviews = [  
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
    {
        idReview: "R56",
        idC: "C521" ,
        idGuia:"G56451",
        calificacion: 4.5,
        fecha: "26/11/2020",
        reseña: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam exercitationem dolore, blanditiis atque adipisci eligendi numquam earum, obcaecati dolorum debitis officia commodi eius maiores, perferendis enim ea mollitia animi voluptate?",
    },
];